version: "3.3"

services:
  traefik:
    restart: always
    image: traefik:v2.6
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "172.17.0.1:8080:8080/tcp"  # Expose the internal dashboard on a private IP.
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./letsencrypt:/letsencrypt

  configurator:
    restart: always
    build:
      context: ./aleph_proxy_config
    environment:
      SENTRY_SDK: ""
    ports:
      - "9000:9000/tcp"
    volumes:
      - ./aleph_proxy_config/main.py:/opt/aleph_proxy_config/main.py
      - ./aleph_proxy_config/config.yaml:/opt/aleph_proxy_config/config.yaml
