http:
  routers:

    to-aleph-api:
      rule: "PathPrefix(`/api/`)"
      service: aleph-api
      middlewares:
        - retry-if-no-reply
      tls:
        certResolver: letsencrypt
        domains:
          - main: "aleph.cloud"  # Change to the domain you are using

    to-aleph-vm:
      rule: "PathPrefix(`/vm/`)"
      service: aleph-vm
      middlewares:
        - retry-if-no-reply
      tls:
        certResolver: letsencrypt
        domains:
          - main: "aleph.cloud"  # Change to the domain you are using

  middlewares:
    retry-if-no-reply:
      retry:
        attempts: 4
        initialInterval: 5ms

  services:

    aleph-api:
      loadBalancer:
        healthcheck:
          path: /
          interval: 60s
          timeout: 2s
        passHostHeader: false
        servers:  # These are the initial values, they will be updated from the list of nodes
        - url: https://api1.aleph.im/api/
        - url: https://api2.aleph.im/api/

    aleph-vm:
      loadBalancer:
        healthcheck:
          # fastapi demo path
          path: /vm/67705389842a0a1b95eaa408b009741027964edc805997475e95c505d642edd8
          interval: 60s
          timeout: 10s
        passHostHeader: false
        servers:  # These are the initial values, they will be updated from the list of nodes
        - url: https://aleph.sh/vm/
        - url: https://vm.demo.okeso.fr/vm/
        sticky:
          cookie:
            name: aleph-proxy-sticky-session
