http:
  routers:
    to-aleph-vm-compute-s:  # Forward VM calls to all available Compute Resource Nodes in the network with CPU < 8 and or CPU < 24 and RAM < 16
      rule: "PathPrefix(`/vm-compute-small/`)"
      service: aleph-vm-compute-small
      middlewares:
        - retry-if-no-reply
      tls:
        certResolver: letsencrypt
        domains:
          - main: "aleph.cloud"  # Change to the domain you are using

    to-aleph-vm-compute-m:  # Forward VM calls to all available Compute Resource Nodes in the network with CPU in [8..16] or CPU > 8 and RAM in [16..<32]
      rule: "PathPrefix(`/vm-compute-medium/`)"
      service: aleph-vm-compute-medium
      middlewares:
        - retry-if-no-reply
      tls:
        certResolver: letsencrypt
        domains:
          - main: "aleph.cloud"  # Change to the domain you are using

    to-aleph-vm-compute-l:  # Forward VM calls to all available Compute Resource Nodes in the network with CPU in [16..32] or CPU > 12 and RAM in [16>..32] 
      rule: "PathPrefix(`/vm-compute-large/`)"
      service: aleph-vm-compute-large
      middlewares:
        - retry-if-no-reply
      tls:
        certResolver: letsencrypt
        domains:
          - main: "aleph.cloud"  # Change to the domain you are using

    to-aleph-vm-compute-xl:  # Forward VM calls to all available Compute Resource Nodes in the network with CPU >= 32 or CPU > 16 and RAM > 32
      rule: "PathPrefix(`/vm-compute-xlarge/`)"
      service: aleph-vm-compute-xlarge
      middlewares:
        - retry-if-no-reply
      tls:
        certResolver: letsencrypt
        domains:
          - main: "aleph.cloud"  # Change to the domain you are using


  middlewares:
    retry-if-no-reply:
      retry:
        attempts: 4
        initialInterval: 5ms

    do-not-add-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Host: "aleph-proxy-homepage.aleph.cloud"
          X-Forwarded-Port: ""
          X-Forwarded-Proto: ""
          X-Forwarded-Server: ""
          X-Real-Ip: ""

  services:
    aleph-vm-compute-small:
      loadBalancer:
        healthcheck:
          # Check the health of Compute Resource Nodes by calling the
          # fastapi demo path
          path: /vm/67705389842a0a1b95eaa408b009741027964edc805997475e95c505d642edd8
          interval: 60s
          timeout: 10s
        passHostHeader: false
        servers:  # These are the initial values, they will be updated from the list of nodes
        - url: https://aleph.sh/vm/
        - url: https://vm.demo.okeso.fr/vm/
        sticky:
          # Clients receive a session cookie that allows them to call the same Compute Resource Node for
          # all calls.
          cookie:
            name: aleph-proxy-compute-sticky-session

    aleph-vm-compute-medium:
      loadBalancer:
        healthcheck:
          # Check the health of Compute Resource Nodes by calling the
          # fastapi demo path
          path: /vm/67705389842a0a1b95eaa408b009741027964edc805997475e95c505d642edd8
          interval: 60s
          timeout: 10s
        passHostHeader: false
        servers:  # These are the initial values, they will be updated from the list of nodes
        - url: https://aleph.sh/vm/
        - url: https://vm.demo.okeso.fr/vm/
        sticky:
          # Clients receive a session cookie that allows them to call the same Compute Resource Node for
          # all calls.
          cookie:
            name: aleph-proxy-compute-sticky-session

    aleph-vm-compute-large:
      loadBalancer:
        healthcheck:
          # Check the health of Compute Resource Nodes by calling the
          # fastapi demo path
          path: /vm/67705389842a0a1b95eaa408b009741027964edc805997475e95c505d642edd8
          interval: 60s
          timeout: 10s
        passHostHeader: false
        servers:  # These are the initial values, they will be updated from the list of nodes
        - url: https://aleph.sh/vm/
        - url: https://vm.demo.okeso.fr/vm/
        sticky:
          # Clients receive a session cookie that allows them to call the same Compute Resource Node for
          # all calls.
          cookie:
            name: aleph-proxy-compute-sticky-session

    aleph-vm-compute-xlarge:
      loadBalancer:
        healthcheck:
          # Check the health of Compute Resource Nodes by calling the
          # fastapi demo path
          path: /vm/67705389842a0a1b95eaa408b009741027964edc805997475e95c505d642edd8
          interval: 60s
          timeout: 10s
        passHostHeader: false
        servers:  # These are the initial values, they will be updated from the list of nodes
        - url: https://aleph.sh/vm/
        - url: https://vm.demo.okeso.fr/vm/
        sticky:
          # Clients receive a session cookie that allows them to call the same Compute Resource Node for
          # all calls.
          cookie:
            name: aleph-proxy-compute-sticky-session
